# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name newey_west_tsls
#' @title Compute 2SLS parameters and robust standard errors based on Newey-West
#' @description  Compute 2SLS parameters and robust standard errors based on Newey and West (1987).
#' Part of the function is based on the Matlab code by James P. LeSage.
#' @param y Numeric vector.
#' @param x Numeric matrix.
#' @param z Numeric matrix.
#' @param h Integer.
#' @return A vector, the 2SLS-Huber-White robust t-statistics for the IV coefficients.
#' @keywords internal
#' @references
#' Newey, W.K., and West, K.D. (1987). “A Simple, Positive-Definite, Heteroskedasticity and
#' Autocorrelation Consistent Covariance Matrix.” \emph{Econometrica}, 55, 703–708.
#' Wooldridge, J.M. (2002), Econometric Analysis of Cross Section and Panel Data, The MIT Press.
huber_white_tsls_tstats <- function(y, x, z) {
    .Call(`_riiv_huber_white_tsls_tstats`, y, x, z)
}

ranktestU <- function(y, t) {
    .Call(`_riiv_ranktestU`, y, t)
}

ri_iv_test_p <- function(b, y, x, z, r = 1000L, seed = 1234L, mode = 0L) {
    .Call(`_riiv_ri_iv_test_p`, b, y, x, z, r, seed, mode)
}

