# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ranktestU <- function(y, t) {
    .Call(`_riiv_ranktestU`, y, t)
}

ri_iv_test_p <- function(b, y, x, z, r = 1000L, seed = 12345L, ranktest = FALSE) {
    .Call(`_riiv_ri_iv_test_p`, b, y, x, z, r, seed, ranktest)
}

